version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: medibot-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # Supabase variables will be loaded from .env file
      - JWT_SECRET=your-jwt-secret-key
      - AI_SERVICE_API_KEY=your-ai-service-api-key
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - medibot-network

networks:
  medibot-network:
    driver: bridge