services:
  livekit-agent:
    build: ./agent
    container_name: medical-consultation-agent
    environment:
      # LiveKit Configuration
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      
      # AI Provider Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - CARTESIA_API_KEY=${CARTESIA_API_KEY}
      
      # Agent Configuration
      - AGENT_NAME=medical-consultation-agent
      - AGENT_DESCRIPTION=Medical consultation agent in Spanish
      
      # Logging
      - LOG_LEVEL=INFO
    volumes:
      # Persist model files
      - ./agent/models:/app/models
      # Mount logs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; print('Agent health check passed'); sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - medical-network

networks:
  medical-network:
    driver: bridge

volumes:
  agent-models:
    driver: local
